# Linear Algebra and Numpy

__Review__

dot function과 inner function 다릅니다   
Linear Algebra로 제일 잘 표현한 라이브러리가 Numpy 입니다.    
그래서 Numpy를 사용하고,  
Core에 여러가지가 있고 SubModules에도 다양한 것들이 있는데 Linear Algebra 서브모듈이 정말로 좋습니다.   
Numpy는 사실 SciPy에서 나온겁니다.  
Matrix에 관한거 다 들어있어요 Scipy위에서 만들어진거에요  
  

In [2]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [4]:
np.corrcoef(a2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a=np.array([1,4,5,8],float)
print(a)
type(a)

[1. 4. 5. 8.]


numpy.ndarray

In [17]:
print(a.mean())#nd.nparray에만 가능해요
print(a.var())

2.5
2.9166666666666665


In [40]:
#numpy vecor
#벡터 내적에서는 mp.dot() 과 np.inner()가 같아요
#매트릭스 곱은 np.dot() 혹은 np.matmult()입니다.
b=np.array([[1,0],[0,1],[0,1]])
np.matmul(a,b)

array([[ 29,  40],
       [  9,  17],
       [162, 330]])

In [41]:
a=np.array([[29,25,15],[9,10,7],[162,125,205]])
b=np.array([[.02,.60,.02],[0.02,0.55,0.01],[0.01,0.42,0.02]])
np.matmul(a,b)

array([[  1.23,  37.45,   1.13],
       [  0.45,  13.84,   0.42],
       [  7.79, 252.05,   8.59]])

In [42]:
a@b

array([[  1.23,  37.45,   1.13],
       [  0.45,  13.84,   0.42],
       [  7.79, 252.05,   8.59]])

In [43]:
np.dot(a,b)

array([[  1.23,  37.45,   1.13],
       [  0.45,  13.84,   0.42],
       [  7.79, 252.05,   8.59]])

# Advanced Linear Algebara

In [47]:
#Matrix Determinent
np.linalg.det(a)

8875.000000000004

In [2]:
import pprint
import scipy
import scipy.linalg #scipy linear algebra lib
A=scipy.array([[7,3,-1,2],[3,8,1,-4],[-1,1,4,-1],[2,-4,-1,6]])
P,L,U=scipy.linalg.lu(A)
pprint.pprint(A)
pprint.pprint(P)
pprint.pprint(L)
pprint.pprint(U)

array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])
array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])


In [4]:
#LU Decomposition
#Lower Triangular Matrix
#Upper Triangular Matrix
#numpy에는 LU구하려면 복잡하고, Scipy에 있어요.
A=np.array([[2,1,1],[4,-6,0],[-2,7,2]])
from scipy import linalg
_,L,U=linalg.lu(A)

리턴하는 값중에서 내가 사용 안하겠다 하면 _로 표현합니다.   
LU가 필요한건 기본적인 일인데  
Numpy에서 직접 지원 안하고 Scipy에서 지원합니다.  
Lu가 왜 중요할까요? Decomposition이 중요한 일이고,  
연관해서 배웠던 Eigen matrix구하는 식이나 SVD도 다 Decomposition도 연결됩니다. 가장 기초가되는게 LU에요  
Python에서 Matrix표현하려면 [[3,4],[5,6]] 이런식으로해요  
numpy에서는 array([[3,4],[5,6]]) 에서의 matrix에요  
Scipy도 Scipy array가 있어요. scipy.array([[3,4],[5,6]]) 이 있고 array~ 로 나옵니다 출력하면   
그래서 numpy랑 똑같은거에요  

In [5]:
print(_)
print(np.linalg.inv(_)) #P matrix는 P의 역행렬과 같은 행렬입니다.

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [11]:
print('L = \n'+str(L))
print('U = \n'+str(U))
print('LU = \n'+str(np.matmul(L,U)))

L = 
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5  1.   1. ]]
U = 
[[ 4. -6.  0.]
 [ 0.  4.  1.]
 [ 0.  0.  1.]]
LU = 
[[ 4. -6.  0.]
 [ 2.  1.  1.]
 [-2.  7.  2.]]


In [6]:
#EigenDecomposition
import numpy as np
import numpy.linalg as LA
c=np.array([[3,0],[8,-1]])
w,v=LA.eig(c)
print(w) #Eigen Value
print(v) #Eigen vectors

[-1.  3.]
[[0.         0.4472136 ]
 [1.         0.89442719]]


In [7]:
l=np.diag(w)#람다행렬 만들기 
i=LA.inv(v)#V의 inverse 만들어주기.

In [8]:
np.dot(np.dot(v,l),i) #inv(V)*Lambda*V 하면 원래 행렬 c가 나옵니다.

array([[ 3.,  0.],
       [ 8., -1.]])

In [9]:
np.dot(np.dot(v,l),i) ==c

array([[ True,  True],
       [ True,  True]])

In [21]:
#SVD Vector Decomposition In Python
#데이터 분석을 할적에 잠재적인 성향의 데이터를 찾아내면 잠재적인 성향의 데이터를 찾지않고 추천하는것보다
#잠재적인 성향을 이용하는 것이 추천이 좀더 파워풀해진다.
#SVD를 이용해서 주성분 분석하면 된다.
#아이겐밸류들이 내림차순인 대각행렬이 생성되는데 
#예제에서는  5개의 람다중에 (의미가 가장 큰 )3개만 사용합니다.
#이말은 U행렬의 3열까지, V의 Transposegodfufdml 3행까지 사용한다는 의미입니다.
user=np.array([[4,3,2,5,1],[0,3,0,4,2],[5,4,3,3,0],[0,0,5,5,2],[5,0,0,5,0]])
#numpy.linalg.svd(user,full_matirces=1,compute_uv=1)#full_matrix는 정방형 행렬이다.

A=np.zeros((5,5))
A[0,4]=1
A[0,1]=A[1,4]=A[3,4]=2
A[0,2]=A[1,1]=A[2,2]=A[2,3]=3
A[0,0]=A[1,3]=A[2,1]=4
A[0,3]=A[2,0]=A[3,2]=A[3,3]=A[4,0]=A[4,3]=5
print(A)

[[4. 2. 3. 5. 1.]
 [0. 3. 0. 4. 2.]
 [5. 4. 3. 3. 0.]
 [0. 0. 5. 5. 2.]
 [5. 0. 0. 5. 0.]]


In [22]:
U,s,V=np.linalg.svd(A,full_matrices=True)#정방형 행렬
S3=np.zeros((5,5))
S3[:3,:3]=np.diag(s[:3])
P=np.dot(U,np.dot(S3,V))

In [23]:
print(P)

[[ 3.86264834  2.10095953  2.72622203  5.20675638  0.98813798]
 [ 0.81623697  2.30268631  2.35653282  2.60401312  1.14619552]
 [ 4.65694642  4.30103317  1.94991181  3.60039781  0.43443858]
 [-0.25418055  0.22314233  4.22123158  5.44502131  2.32280423]
 [ 5.26537027 -0.22144214  0.72668687  4.55519258 -0.22759672]]


# Pandas
---------------------------------

## Why Pandas?
SQL에서 배운 관계형 데이터베이스를 다루는 방법인 realtional algebra,   
편리했던 SQL에서의 경험을 판다스를 이용해서 또 데이터를 집어넣고 하면 편할것 같아서 만든겁니다.   

## Pandas Series Object
## Pandas DataFrame Object
## Pandas Panel Object
## Time Series Data in Pandas
편하게 잘 다룰수있습니다 판다스에서요.

## IO in Pandas
## Pandas Function List



------------------------------
###  Pandas Series Object

In [24]:
#Limitation of Numpy Object
#Content Base로 데이터에 접근한다.
a=np.array([[1,2,3],[4,5,6]],float)
a[1,:]

array([4., 5., 6.])

Table 두개의 Join을 하려면 어떻게 해야하나..? Numpy에서 하려면요..   
이게 어려워요. 그래서 SQL에서 아예 가져오려고 하거나 합니다.  
판다스의 모티베이션이 이것입니다. 파이썬에서 데이터를 직접 다루고 싶어서입니다.  

data series가 1차원데이터  
data frame이 2차원 테이블입니다   
data base table과 같아요.   

In [25]:
#Pandas 에서 제공하는 Data Type
#Panel은 3~5차원입니다.
a=[3,4,7]
b=np.array(a)
b

array([3, 4, 7])

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
s=pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Pandas는 오토매틱 Indexing을 지원합니다  
왜 이게있을까요? 당연히! 옆에다가   
인덱스 정보를 걸어놓아서   
데이터 가져오기 편하게 하기위해서입니다.

In [27]:
np_s=np.array([1,3,5,np.nan,6,8])
pd_s=pd.Series(np_s)
pd_s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [28]:
d={'a':0.,'b':1.,'c':2.} #실수표현
pd.Series(d)

a    0.0
b    1.0
c    2.0
dtype: float64

In [29]:
from pandas import Series, DataFrame
import pandas as pd
sdata={'Ohio':35000,'Texas':71000,'Oregon':16000,'Utah':5000}
obj3=Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
states=['California','Ohio','Oregon','Texas']
obj4=Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

판다스로 표현할 적에는      
유타는 아예 나타나질 않았고,      
캘리포니아는 값이 없었으므로      
NaN처리 해서 나타냅니다.     
Dictionary의 키값이 Unique하므로   
인덱스로 써서 만들어주면      
얘들은 키 역할을 할수있습니다.  

In [31]:
#결과는 같아요
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [33]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [34]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

### Pandas DataFrame Object
인덱스 기반으로 되어있는것이 Pandas Series Object입니다

In [35]:
sales_states={'Day':[1,2,3,4,5,6],
              'Visitors':[43,45,33,43,78,44],
              'Revenues':[64,73,62,64,53,66]}

In [36]:
df=pd.DataFrame(sales_states)
df

Day  Visitors  Revenues
0    1        43        64
1    2        45        73
2    3        33        62
3    4        43        64
4    5        78        53
5    6        44        66

인덱싱도 또 다 해줍니다  
생성된 Index들은 Label이라고도 불리지만,  
주로 index로 불립니다.  
  
2차원 리스트가 들어갈수도있고,  
혹은 딕셔너리가 들어갈수도 있습니다.  
Day,Visitors, Revenues는 Column이라고 불립니다.  
df[col]: select column  
df.loc[label] : select row by label  
df.iloc[loc]: select row by integer location  
df[5:10]: slice rows  
df[bool_vec] : Select rows by boolean vector  

In [37]:
df.loc[0]

Day          1
Visitors    43
Revenues    64
Name: 0, dtype: int64

In [38]:
df.loc[:3] #Pandas는 마지막 3도 포함합니다.

Day  Visitors  Revenues
0    1        43        64
1    2        45        73
2    3        33        62
3    4        43        64

In [39]:
df=df.set_index('Day') #인덱스를 Day로 교체해줬습니다. 유니크하니까 상관없지용!
df

Visitors  Revenues
Day                    
1          43        64
2          45        73
3          33        62
4          43        64
5          78        53
6          44        66

In [40]:
df.iloc[1]#자동으로 매겨놓은 index기반입니다.(0,1,2,3에서의 입니다.)

Visitors    45
Revenues    73
Name: 2, dtype: int64

In [41]:
df.loc[1] #Index기반입니다. 인덱스에 들어있는 값을 기반으로 해서 찾아줍니다. Day가 1인걸 찾아줍니다.

Visitors    43
Revenues    64
Name: 1, dtype: int64

In [42]:
sales_stats={'Visitors':[43,45,33,43,78,44],
             'Revenue':[64,73,62,64,53,66]}

In [43]:
df2=pd.DataFrame(sales_stats,index=['a','b','c','d','e','f'])
df2


Visitors  Revenue
a        43       64
b        45       73
c        33       62
d        43       64
e        78       53
f        44       66

In [44]:
df2.loc['f']
df2.loc['c':'e']

Visitors  Revenue
c        33       62
d        43       64
e        78       53

In [45]:
df2.iloc[3:5]

Visitors  Revenue
d        43       64
e        78       53

In [46]:
#나는 revenue가 65초과인 행만 원해!
#SQl에서 Where절에 조건 추가하는 것처럼 합니다.
df2[df2['Revenue']>65]

Visitors  Revenue
b        45       73
f        44       66

In [47]:
df2[(df2['Revenue']>65)|(df2['Visitors']>70)]

Visitors  Revenue
b        45       73
e        78       53
f        44       66

## 추가부분. Linear Algebra 부분입니다. (7/31 포함)

In [50]:
#SVD추가하세요. 

In [54]:
df2['Visitors'] #Visitor만 튀어나오는게 아니라 Index도 같이 튀어나옵니다.

a    43
b    45
c    33
d    43
e    78
f    44
Name: Visitors, dtype: int64

In [55]:
df2[['Visitors','Revenue']]

Visitors  Revenue
a        43       64
b        45       73
c        33       62
d        43       64
e        78       53
f        44       66

In [56]:
DataFrame(df2,columns=['Visitors','Revenue'])

Visitors  Revenue
a        43       64
b        45       73
c        33       62
d        43       64
e        78       53
f        44       66

In [57]:
DataFrame(df2,columns=['Revenue','Visitors'])

Revenue  Visitors
a       64        43
b       73        45
c       62        33
d       64        43
e       53        78
f       66        44

In [58]:
#새로운 컬럼 추가하기
DataFrame(df2,columns=['Visitors','Revenue','Debt'])

Visitors  Revenue  Debt
a        43       64   NaN
b        45       73   NaN
c        33       62   NaN
d        43       64   NaN
e        78       53   NaN
f        44       66   NaN

In [63]:
df3=DataFrame(df2,columns=['Visitors','Revenue','Debt'])
del df3['Debt'] 
#df3.drop('Debt',axis=1) #각 Row에 입니다. 
#날릴수있어요 del이 전부다 날릴수가있어요 한 컬럼도 날릴수 있습니다.
df3

Visitors  Revenue
a        43       64
b        45       73
c        33       62
d        43       64
e        78       53
f        44       66

In [64]:
df3

Visitors  Revenue
a        43       64
b        45       73
c        33       62
d        43       64
e        78       53
f        44       66

In [65]:
#Add a New Row
df3.loc['h']=[200,77]

In [66]:
#Delete an existing row
df3
df3.drop('h',axis=0)#각 column에 대해서 입니다.

Visitors  Revenue
a        43       64
b        45       73
c        33       62
d        43       64
e        78       53
f        44       66

In [67]:
#Rename Row/Column in DataFrame Object
Change_dict={'old_name1':'new_name1'}

In [68]:


newcols={'A':'new_col_1','B':'new_col_2','c':'new_col_3'}
newcols

{'A': 'new_col_1', 'B': 'new_col_2', 'c': 'new_col_3'}

In [69]:
df.rename(columns=newcols)

Visitors  Revenues
Day                    
1          43        64
2          45        73
3          33        62
4          43        64
5          78        53
6          44        66

In [70]:
df2[df2['Revenue']>65].count()


Visitors    2
Revenue     2
dtype: int64

In [71]:
df2['Revenue'].mean

<bound method Series.mean of a    64
b    73
c    62
d    64
e    53
f    66
Name: Revenue, dtype: int64>

In [72]:
df2.cov()

Visitors    Revenue
Visitors  239.866667 -67.133333
Revenue   -67.133333  41.866667

In [73]:
#iterrow()
df=pd.DataFrame(data=np.array([[1,2,3],[4,5,6],[7,8,9]]),columns=['A','B','C'])
df

A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [74]:
for index,row in df.iterrows():
    print(row['A'],row['B'])

1 2
4 5
7 8


In [75]:
df=pd.DataFrame({'A':['foo','bar','foo','bar','foo','bar','foo','foo'],
                'B':['one','one','two','three','two','two','one','three'],'C':np.random.randn(8), 'D':np.random.randn(8)})

In [76]:
df# Group 묶고싶어요 A는 foo는 foo끼리 Bar는 bar끼리! B는 one과 two three로!

A      B         C         D
0  foo    one  2.240103 -0.202057
1  bar    one -0.462776  0.594940
2  foo    two -0.042305 -0.093176
3  bar  three -0.950721 -0.102697
4  foo    two  1.250494 -0.590762
5  bar    two  0.174202 -1.673193
6  foo    one -0.182196  0.901759
7  foo  three  1.343191 -0.014529

In [77]:
grouped=df.groupby('A') #A컬럼가지고 그룹핑을 합니다.
grouped

In [78]:
print(grouped)

In [79]:
print(grouped.mean())
grouped.sum()

            C         D
A                      
bar -0.413098 -0.393650
foo  0.921858  0.000247


C         D
A                      
bar -1.239295 -1.180951
foo  4.609288  0.001235

In [80]:
#동시에 두개 그루핑
grouped2=df.groupby(['A','B'])

In [81]:
grouped2.mean()

C         D
A   B                        
bar one   -0.462776  0.594940
    three -0.950721 -0.102697
    two    0.174202 -1.673193
foo one    1.028954  0.349851
    three  1.343191 -0.014529
    two    0.604095 -0.341969

In [82]:
grouped.get_group('bar')

B         C         D
1    one -0.462776  0.594940
3  three -0.950721 -0.102697
5    two  0.174202 -1.673193

In [83]:
#관계형 데이터베이스 테이블 조인과같은게 하고싶어!
result=pd.merget(left,righ,on='key')

AttributeError: module 'pandas' has no attribute 'merget'

## Pandas Panel Object

In [87]:
import numpy as np
import pandas as pd
data=np.random.rand(2,4,3)
p=pd.Panel(data)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


In [88]:
p

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 3 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 2

In [89]:
print(p)
print(p.values)

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 3 (minor_axis)
Items axis: 0 to 1
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 2
[[[0.58789384 0.27575023 0.7695084 ]
  [0.35526529 0.01041397 0.75599727]
  [0.817176   0.72948262 0.41288967]
  [0.69657838 0.51078702 0.92185745]]

 [[0.04611486 0.7804675  0.12919432]
  [0.17448411 0.38441809 0.95926685]
  [0.0214072  0.2076429  0.2354935 ]
  [0.18328512 0.62777759 0.44134325]]]


## Time Series Data in Pandas

In [90]:
pd.DatetimeIndex(['2018-01-01','2018-01-04','2018-01-05','2018-01-06'],dtype='datetime64[ns]',freq=None)

DatetimeIndex(['2018-01-01', '2018-01-04', '2018-01-05', '2018-01-06'], dtype='datetime64[ns]', freq=None)

In [91]:
pd.datetime(2017,6,29,16,26,49,626987)

datetime.datetime(2017, 6, 29, 16, 26, 49, 626987)

In [92]:
import datetime
datetime.datetime(2017,6,29,15,26,49,626987)

datetime.datetime(2017, 6, 29, 15, 26, 49, 626987)

In [93]:
from datetime import datetime
today=datetime.today()
print(today)
today

2018-08-01 11:11:06.736775


datetime.datetime(2018, 8, 1, 11, 11, 6, 736775)

In [94]:
date_str=["2018, 1, 1", "2018, 1, 4" ,"2018, 1, 5","2018, 1, 6"]
idx=pd.to_datetime(date_str)
idx

DatetimeIndex(['2018-01-01', '2018-01-04', '2018-01-05', '2018-01-06'], dtype='datetime64[ns]', freq=None)

In [95]:
pd.date_range("2018-4-1","2018-4-30")

DatetimeIndex(['2018-04-01', '2018-04-02', '2018-04-03', '2018-04-04',
               '2018-04-05', '2018-04-06', '2018-04-07', '2018-04-08',
               '2018-04-09', '2018-04-10', '2018-04-11', '2018-04-12',
               '2018-04-13', '2018-04-14', '2018-04-15', '2018-04-16',
               '2018-04-17', '2018-04-18', '2018-04-19', '2018-04-20',
               '2018-04-21', '2018-04-22', '2018-04-23', '2018-04-24',
               '2018-04-25', '2018-04-26', '2018-04-27', '2018-04-28',
               '2018-04-29', '2018-04-30'],
              dtype='datetime64[ns]', freq='D')

In [96]:
#2018-04-01부터 30일!
pd.date_range("2018-4-1",periods=30)

DatetimeIndex(['2018-04-01', '2018-04-02', '2018-04-03', '2018-04-04',
               '2018-04-05', '2018-04-06', '2018-04-07', '2018-04-08',
               '2018-04-09', '2018-04-10', '2018-04-11', '2018-04-12',
               '2018-04-13', '2018-04-14', '2018-04-15', '2018-04-16',
               '2018-04-17', '2018-04-18', '2018-04-19', '2018-04-20',
               '2018-04-21', '2018-04-22', '2018-04-23', '2018-04-24',
               '2018-04-25', '2018-04-26', '2018-04-27', '2018-04-28',
               '2018-04-29', '2018-04-30'],
              dtype='datetime64[ns]', freq='D')

In [97]:
pd.date_range("2018-4-1","2018-4-30",freq="B") #주말이 아닌 평일

DatetimeIndex(['2018-04-02', '2018-04-03', '2018-04-04', '2018-04-05',
               '2018-04-06', '2018-04-09', '2018-04-10', '2018-04-11',
               '2018-04-12', '2018-04-13', '2018-04-16', '2018-04-17',
               '2018-04-18', '2018-04-19', '2018-04-20', '2018-04-23',
               '2018-04-24', '2018-04-25', '2018-04-26', '2018-04-27',
               '2018-04-30'],
              dtype='datetime64[ns]', freq='B')

In [98]:
pd.date_range("2018-1-1","2018-12-31",freq="W") #주(일요일)

DatetimeIndex(['2018-01-07', '2018-01-14', '2018-01-21', '2018-01-28',
               '2018-02-04', '2018-02-11', '2018-02-18', '2018-02-25',
               '2018-03-04', '2018-03-11', '2018-03-18', '2018-03-25',
               '2018-04-01', '2018-04-08', '2018-04-15', '2018-04-22',
               '2018-04-29', '2018-05-06', '2018-05-13', '2018-05-20',
               '2018-05-27', '2018-06-03', '2018-06-10', '2018-06-17',
               '2018-06-24', '2018-07-01', '2018-07-08', '2018-07-15',
               '2018-07-22', '2018-07-29', '2018-08-05', '2018-08-12',
               '2018-08-19', '2018-08-26', '2018-09-02', '2018-09-09',
               '2018-09-16', '2018-09-23', '2018-09-30', '2018-10-07',
               '2018-10-14', '2018-10-21', '2018-10-28', '2018-11-04',
               '2018-11-11', '2018-11-18', '2018-11-25', '2018-12-02',
               '2018-12-09', '2018-12-16', '2018-12-23', '2018-12-30'],
              dtype='datetime64[ns]', freq='W-SUN')

In [99]:
#타임스탬프주고 5일동안!
pd.date_range(start='9/28/2016 16:00',periods=5)

DatetimeIndex(['2016-09-28 16:00:00', '2016-09-29 16:00:00',
               '2016-09-30 16:00:00', '2016-10-01 16:00:00',
               '2016-10-02 16:00:00'],
              dtype='datetime64[ns]', freq='D')

In [100]:
pd.date_range(start='1/1/2016',end='1/1/2017',freq="2BMS")

DatetimeIndex(['2016-01-01', '2016-03-01', '2016-05-02', '2016-07-01',
               '2016-09-01', '2016-11-01'],
              dtype='datetime64[ns]', freq='2BMS')

In [101]:
pd.date_range(start="9/28/2016 16:00",end='9/29/2016 16:30',freq='10T')

DatetimeIndex(['2016-09-28 16:00:00', '2016-09-28 16:10:00',
               '2016-09-28 16:20:00', '2016-09-28 16:30:00',
               '2016-09-28 16:40:00', '2016-09-28 16:50:00',
               '2016-09-28 17:00:00', '2016-09-28 17:10:00',
               '2016-09-28 17:20:00', '2016-09-28 17:30:00',
               ...
               '2016-09-29 15:00:00', '2016-09-29 15:10:00',
               '2016-09-29 15:20:00', '2016-09-29 15:30:00',
               '2016-09-29 15:40:00', '2016-09-29 15:50:00',
               '2016-09-29 16:00:00', '2016-09-29 16:10:00',
               '2016-09-29 16:20:00', '2016-09-29 16:30:00'],
              dtype='datetime64[ns]', length=148, freq='10T')

In [102]:
pd.date_range(start="9/28/2016 16:30",periods=5,freq="2h30min")


DatetimeIndex(['2016-09-28 16:30:00', '2016-09-28 19:00:00',
               '2016-09-28 21:30:00', '2016-09-29 00:00:00',
               '2016-09-29 02:30:00'],
              dtype='datetime64[ns]', freq='150T')

In [103]:
rng=pd.date_range('1/1/2011',periods=72,freq='H')

In [104]:
rng[:5]

DatetimeIndex(['2011-01-01 00:00:00', '2011-01-01 01:00:00',
               '2011-01-01 02:00:00', '2011-01-01 03:00:00',
               '2011-01-01 04:00:00'],
              dtype='datetime64[ns]', freq='H')

In [105]:
ts=pd.Series(np.random.randn(len(rng)),index=rng)

In [106]:
ts.head() #head는 앞에 5개만

2011-01-01 00:00:00   -0.595667
2011-01-01 01:00:00    0.529828
2011-01-01 02:00:00    0.484047
2011-01-01 03:00:00    1.282062
2011-01-01 04:00:00    2.212230
Freq: H, dtype: float64

In [107]:
#ts.tale 고민해봐ㅛ

In [108]:
pd.Series(['Jul 31,2009','2010-01-10',None])

0    Jul 31,2009
1     2010-01-10
2           None
dtype: object

In [109]:
#pd.to_datetime(pd.Series(['Jul 31,2009','2010-01-10',None]))
#왜 안되는거야 도대체

In [110]:
rng=pd.date_range('1/1/2011',periods=72,freq="H")


In [111]:
ts=pd.Series(np.random.randn(len(rng)),index=rng)
ts.head()

2011-01-01 00:00:00   -0.633811
2011-01-01 01:00:00   -1.949768
2011-01-01 02:00:00    0.432130
2011-01-01 03:00:00    0.668757
2011-01-01 04:00:00   -0.566963
Freq: H, dtype: float64

In [112]:
#끝나는 시점~
ts.truncate(before='01/02/2011',after='01/03/2011');

In [113]:

from datetime import datetime
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as pyplot
data={'date':['2014-05-01 18:47:05.0597229']}