# Ch31. Numpy

In [163]:
import numpy as np

## Numpy Array Creation

In [17]:
a=np.array([1,4,5,8],float)
print(a)
type(a)

[ 1.  4.  5.  8.]


numpy.ndarray

In [18]:
import array
a=array.array("i",[3,6,9])
a,type(a)

(array('i', [3, 6, 9]), array.array)

In [19]:
b=array.array('u',"boy")
b,type(b)

(array('u', 'boy'), array.array)

In [23]:
a=np.array([[1,2,3],[4,5,6]],float)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [24]:
a[0,0]

1.0

In [25]:
a[0,1]

2.0

In [28]:
#a=np.array(1,2,3,4) Wrong
a=np.array([1,2,3,4])#Right!
a

array([1, 2, 3, 4])

In [30]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [31]:
np.arange(0,2,0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [34]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [35]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [39]:
#7로 가득 채워서 3 x 3 행렬만들기
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [40]:
#Identity mat 만들기
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [43]:
np.random.random((3,3)) 
#np.random.rand(3,3) 같은겁니다.

array([[ 0.02034413,  0.6295685 ,  0.62843425],
       [ 0.60950502,  0.85080251,  0.12179305],
       [ 0.02849988,  0.05018132,  0.26865121]])

In [44]:
a3=np.array([[1,2,3],[4,5,6]],float)
a3

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [46]:
a4=np.array([1,2,3,'four','five'])
a4

array(['1', '2', '3', 'four', 'five'], 
      dtype='<U21')

In [48]:
type(a3),type(a4)

(numpy.ndarray, numpy.ndarray)

## Numpy Array Manipulation

In [49]:
a=np.array([[1,2,3],[4,5,6]],float)

In [54]:
#a[행,열]
a[1,:]

array([ 4.,  5.,  6.])

In [51]:
a[:,2]

array([ 3.,  6.])

In [53]:
a[-1:,-1:]

array([[ 6.]])

In [52]:
a[-1:,-2:]

array([[ 5.,  6.]])

In [55]:
a=np.array(range(6),float).reshape((2,3))
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [56]:
a.transpose()

array([[ 0.,  3.],
       [ 1.,  4.],
       [ 2.,  5.]])

In [58]:
a=np.array([[1,2,3],[4,5,6]],float)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [59]:
a.flatten()

array([ 1.,  2.,  3.,  4.,  5.,  6.])

In [60]:
a=np.array([1,2],float)
b=np.array([3,4,5,6],float)
c=np.array([7,8,9],float)
np.concatenate((a,b,c))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [61]:
a=np.array([1,2,3],float)
b=np.array([5,2,6],float)
a+b

array([ 6.,  4.,  9.])

In [62]:
a-b

array([-4.,  0., -3.])

In [63]:
a*b

array([  5.,   4.,  18.])

In [64]:
b/a

array([ 5.,  1.,  2.])

In [65]:
a%b

array([ 1.,  0.,  3.])

In [66]:
b**a

array([   5.,    4.,  216.])

__Numpy Array Mathematics__

In [67]:
a=np.array([1,2,3],float)
b=np.array([4,5,6],float)
a+b

array([ 5.,  7.,  9.])

In [70]:
b2=np.array([4,5,6,7],float)
#a+b2, b2/a, b2 **a 전부다 불가능합니다. shape이 다르기때문.

__list+list는 concatenate가 됩니다.__

In [71]:
a=[1,2,3,4]
a*2

[1, 2, 3, 4, 1, 2, 3, 4]

__np,array+np.array는 성분별 연산이 됩니다.__

In [72]:
npa=np.array(a)
npa*2

array([2, 4, 6, 8])

In [73]:
a=np.array([1,4,5],int)
for x in a:
    print(x)

1
4
5


In [75]:
a=np.array([[1,2],[3,4],[5,6]],float)
for x in a:
    print(x)

[ 1.  2.]
[ 3.  4.]
[ 5.  6.]


In [79]:
a=np.arange(1,19).reshape(3,2,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [80]:
for x in a:
    print(x)
    print('------')

[[1 2 3]
 [4 5 6]]
------
[[ 7  8  9]
 [10 11 12]]
------
[[13 14 15]
 [16 17 18]]
------


In [81]:
for x in a:
    for y in x:
        print(y)
        print('------')

[1 2 3]
------
[4 5 6]
------
[7 8 9]
------
[10 11 12]
------
[13 14 15]
------
[16 17 18]
------


## Numpy Array Statistics

In [157]:
a=np.array([2,4,3],float)
print(a.sum())
print(a.prod()) #전부다 곱함

9.0
24.0


In [158]:
a=np.array([2,1,9],float)
print(a.mean())#nd.nparray에만 가능해요
print(a.var())
print(a.std())

4.0
12.6666666667
3.55902608401


In [159]:
a=np.array([1,4,3,8,9,2,3],float)
np.median(a)

3.0

In [160]:
x=np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x,axis=0)) #axis=0 열 합
print(np.sum(x,axis=1)) #axis=1 행 합

10
[4 6]
[3 7]


In [161]:
npa=np.arange(1,10).reshape(3,3)
print(npa)
npa.sum()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [104]:
#Python list로 하면 힘듭니다.
def nested_sum(L):
    total=0
    for i in L:
        if isinstance(i,list):
            total+=nested_sum(i)
        else:
            total+=i
    return total
a=[[1,2,3],[4,5,6],[7,8,9]]
nested_sum(a)

45

__공분산,상관계수__

In [107]:
a=np.array([[1,2,1,3],[5,3,1,8]],float)
c=np.corrcoef(a)
c

array([[ 1.        ,  0.72870505],
       [ 0.72870505,  1.        ]])

In [108]:
np.cov(a)

array([[ 0.91666667,  2.08333333],
       [ 2.08333333,  8.91666667]])

In [105]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [106]:
np.corrcoef(a2)

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

## Linear Algebra and Numpy

__a와 b가 1D Array이면, dot은 inner product of vectors 이다.__

In [164]:
a=np.array([1,2,3],float)
b=np.array([0,1,1],float)
np.dot(a,b)

5.0

__일반적으로 1D array의 inner product of vectors는  np.inner(a,b)=sum(a[:] * b[:]) 가 됩니다.__

In [165]:
a=np.array([1,2])
b=np.array([0,3])
np.inner(a,b)

6

__a혹은 b가 scalr일 경우입니다.__

In [166]:
a=np.array([1,2])
np.inner(a,3)

array([3, 6])

__Vector Outer Product__

In [167]:
a=np.array([1,4,0],float)
b=np.array([2,2,1],float)
np.outer(a,b)

array([[ 2.,  2.,  1.],
       [ 8.,  8.,  4.],
       [ 0.,  0.,  0.]])

__Cross Product__

In [168]:
np.cross(a,b)

array([ 4., -1., -6.])

__np.dot 행렬곱__

In [169]:
a=np.array([[0,1],[2,3]],float)
b=np.array([2,3],float)
c=np.array([[1,1],[4,5]],float)

np.dot(b,a)

array([  6.,  11.])

In [170]:
np.dot(a,b)

array([  3.,  13.])

In [171]:
np.dot(a,c)

array([[  4.,   5.],
       [ 14.,  17.]])

In [172]:
np.dot(c,a)

array([[  2.,   4.],
       [ 10.,  19.]])

In [173]:
np.matmul(c,a)

array([[  2.,   4.],
       [ 10.,  19.]])

In [174]:
c@a

array([[  2.,   4.],
       [ 10.,  19.]])

__Matrix Inner Product__

In [175]:
a=np.array([[0,1],[2,3]],float)
b=np.array([[1,1],[4,0]],float)

__np.inner와 np.dot의 결과가 다릅니다.__

In [176]:
np.inner(a,b) #a와 b의 각 행별 곱의 합

array([[ 1.,  0.],
       [ 5.,  8.]])

In [177]:
np.dot(a,b) #행렬 곱

array([[  4.,   0.],
       [ 14.,   2.]])

In [178]:
a=np.array([[[0,1],[2,3]],[[1,1],[4,0]]],float) 
b=np.array([[1,1],[4,0]],float)
np.inner(a,b)

array([[[  1.,   0.],
        [  5.,   8.]],

       [[  2.,   4.],
        [  4.,  16.]]])

In [179]:
np.dot(a,b)

array([[[  4.,   0.],
        [ 14.,   2.]],

       [[  5.,   1.],
        [  4.,   4.]]])

__matrix data type in numpy__

In [146]:
a=np.mat('4 3;2 1')
b=np.mat('1 2; 3 4')

In [147]:
a

matrix([[4, 3],
        [2, 1]])

In [148]:
b

matrix([[1, 2],
        [3, 4]])

In [149]:
print(a*b)

[[13 20]
 [ 5  8]]


In [151]:
c=np.array([[4,3],[2,1]])
d=np.array([[1,2],[3,4]])

In [152]:
print(c*d)#ElementWIse 곱

[[4 6]
 [6 4]]


In [153]:
print(np.dot(c,d))

[[13 20]
 [ 5  8]]


In [154]:
np.matmul(c,d)

array([[13, 20],
       [ 5,  8]])

In [155]:
c@d

array([[13, 20],
       [ 5,  8]])

numpy vecor  
벡터 내적에서는 np.dot() 과 np.inner()가 같아요  
매트릭스 곱은 np.dot() 혹은 np.matmul()입니다.  

__Review__

dot function과 inner function 다릅니다   
Linear Algebra로 제일 잘 표현한 라이브러리가 Numpy 입니다.    
그래서 Numpy를 사용하고,  
Core에 여러가지가 있고 SubModules에도 다양한 것들이 있는데 Linear Algebra 서브모듈이 정말로 좋습니다.   
Numpy는 사실 Scipy에서 나온겁니다.  
Matrix에 관한거 다 들어있어요 Scipy위에서 만들어진거에요  

## Advanced Linear Algebara

### Matrix Determinent

In [180]:
a=np.array([[2,2],[2,2]])
np.linalg.det(a)

0.0

In [181]:
a=np.array([[1,2],[3,4]])
np.linalg.det(a)

-2.0000000000000004

In [183]:
a=np.array([[[1,2],[3,4]],[[4,2],[4,2]],[[1,3],[3,1]]])
np.linalg.det(a)

array([-2.,  0., -8.])

### LU Decomposition

In [185]:
A=np.array([[2,1,1],[4,-6,0],[-2,7,2]])
print('A= \n'+ str(A))
#numpy에는 LU function이 없어요.

A= 
[[ 2  1  1]
 [ 4 -6  0]
 [-2  7  2]]


In [2]:
import pprint
import scipy
import scipy.linalg #scipy linear algebra lib
A=scipy.array([[7,3,-1,2],[3,8,1,-4],[-1,1,4,-1],[2,-4,-1,6]])
P,L,U=scipy.linalg.lu(A)
pprint.pprint(A)
pprint.pprint(P)
pprint.pprint(L)
pprint.pprint(U)

array([[ 7,  3, -1,  2],
       [ 3,  8,  1, -4],
       [-1,  1,  4, -1],
       [ 2, -4, -1,  6]])
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])
array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.42857143,  1.        ,  0.        ,  0.        ],
       [-0.14285714,  0.21276596,  1.        ,  0.        ],
       [ 0.28571429, -0.72340426,  0.08982036,  1.        ]])
array([[ 7.        ,  3.        , -1.        ,  2.        ],
       [ 0.        ,  6.71428571,  1.42857143, -4.85714286],
       [ 0.        ,  0.        ,  3.55319149,  0.31914894],
       [ 0.        ,  0.        ,  0.        ,  1.88622754]])


__LU Decomposition__  
Lower Triangular Matrix  
Upper Triangular Matrix  
numpy에는 LU구하려면 복잡하고, Scipy에 있어요.  

In [4]:
A=np.array([[2,1,1],[4,-6,0],[-2,7,2]])
from scipy import linalg
_,L,U=linalg.lu(A)

리턴하는 값중에서 내가 사용 안하겠다 하면 _로 표현합니다.   
LU가 필요한건 기본적인 일인데,  
Numpy에서 직접 지원 안하고 Scipy에서 지원합니다.  
Lu가 왜 중요할까요? Decomposition이 중요한 일이고,  
연관해서 배웠던 Eigen matrix구하는 식이나 SVD도 다 Decomposition도 연결됩니다.  
가장 기초가되는게 LU에요    
+추가  
Python에서 Matrix표현하려면 [[3,4],[5,6]] 이런식으로해요    
numpy에서는 array([[3,4],[5,6]]) 에서의 matrix에요    
Scipy도 Scipy array가 있어요. scipy.array([[3,4],[5,6]]) 이 있고 array~ 로 나옵니다 출력하면   
그래서 numpy랑 똑같은거에요  

In [5]:
print(_)
print(np.linalg.inv(_)) #P matrix는 P의 역행렬과 같은 행렬입니다.

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


In [11]:
print('L = \n'+str(L))
print('U = \n'+str(U))
print('LU = \n'+str(np.matmul(L,U)))

L = 
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-0.5  1.   1. ]]
U = 
[[ 4. -6.  0.]
 [ 0.  4.  1.]
 [ 0.  0.  1.]]
LU = 
[[ 4. -6.  0.]
 [ 2.  1.  1.]
 [-2.  7.  2.]]


### Eigen Vector and EigenDecomposition

In [192]:
#EigenDecomposition
import numpy as np
import numpy.linalg as LA
c=np.array([[3,0],[8,-1]])
w,v=LA.eig(c)
print(w) #Eigen Value
print(v) #Eigen vectors

[-1.  3.]
[[ 0.          0.4472136 ]
 [ 1.          0.89442719]]


In [193]:
l=np.diag(w)#람다행렬 만들기 
i=LA.inv(v)#V의 inverse 만들어주기.

In [197]:
ED=np.dot(np.dot(v,l),i) #inv(V)*Lambda*V 하면 원래 행렬 c가 나옵니다.
ED

array([[ 3.,  0.],
       [ 8., -1.]])

In [198]:
np.array_equal(c,ED)

True

### Singular Vector Decomposition
SVD Vector Decomposition In Python

데이터 분석을 할적에 잠재적인 성향의 데이터를 찾아내면 잠재적인 성향의 데이터를 찾지않고 추천하는것보다  
잠재적인 성향을 이용하는 것이 추천이 좀더 파워풀해진다.  
SVD를 이용해서 주성분 분석하면 된다.  
아이겐밸류들이 내림차순인 대각행렬이 생성되는데   
예제에서는  5개의 람다중에 (의미가 가장 큰 )3개만 사용합니다.  
이말은 U행렬의 3열까지, V의 Transpose 행렬의 3행까지 사용한다는 의미입니다.

In [205]:
user=np.array([[ 4.,2.,3.,5.,1.],[0.,3.,0.,4.,2.],[5.,4.,3.,3.,0.], [ 0.,0.,5.,5.,2.],[5.,0.,0.,5.,0.]])
#numpy.linalg.svd(user,full_matirces=1,compute_uv=1)#full_matrix는 정방형 행렬이다.

A=np.zeros((5,5))
A[0,4]=1
A[0,1]=A[1,4]=A[3,4]=2
A[0,2]=A[1,1]=A[2,2]=A[2,3]=3
A[0,0]=A[1,3]=A[2,1]=4
A[0,3]=A[2,0]=A[3,2]=A[3,3]=A[4,0]=A[4,3]=5
print(A)

[[ 4.  2.  3.  5.  1.]
 [ 0.  3.  0.  4.  2.]
 [ 5.  4.  3.  3.  0.]
 [ 0.  0.  5.  5.  2.]
 [ 5.  0.  0.  5.  0.]]


In [201]:
U,s,V=np.linalg.svd(A,full_matrices=True)#정방형 행렬
S3=np.zeros((5,5))
S3[:3,:3]=np.diag(s[:3])
P=np.dot(U,np.dot(S3,V))

In [202]:
print(P)

[[ 3.86264834  2.10095953  2.72622203  5.20675638  0.98813798]
 [ 0.81623697  2.30268631  2.35653282  2.60401312  1.14619552]
 [ 4.65694642  4.30103317  1.94991181  3.60039781  0.43443858]
 [-0.25418055  0.22314233  4.22123158  5.44502131  2.32280423]
 [ 5.26537027 -0.22144214  0.72668687  4.55519258 -0.22759672]]
