# Numpy

Numpy 안에는  
CLASS와 FUNCIONT, VARIABLE과 같은 다양한 것들이 들어있어요.
from numpy import *


In [1]:
import numpy as np

In [51]:
a=np.random.random((3,3)) #얘는 튜플로들어갑니다.
a

array([[0.02096599, 0.36307243, 0.91149294],
       [0.60699618, 0.78372726, 0.55302081],
       [0.7966168 , 0.69817986, 0.32178239]])

In [3]:
a=np.random.rand(3,3) #똑같은데, 안에 들어가는게 튜플이 아니에요.
a

array([[0.1194101 , 0.0291429 , 0.71244599],
       [0.98632208, 0.30328654, 0.17505456],
       [0.17128566, 0.39723137, 0.44850144]])

In [4]:
a3=np.array([[1,2,3],[4,5,6]],float)
a3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
a4=np.array([[1,2,3,'four','five']])
a4

array([['1', '2', '3', 'four', 'five']], dtype='<U11')

In [6]:
type(a3)

numpy.ndarray

In [7]:
type(a4)

numpy.ndarray

In [8]:
a=np.array([[1,2,3],[4,5,6]])

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a[1:]

array([[4, 5, 6]])

In [11]:
a[:,2]

array([3, 6])

In [12]:
a[-1:,-2:]

array([[5, 6]])

In [13]:
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
a=np.full((3,3),7)
a

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [16]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
a=np.array(range(6),float).reshape((2,3))
a#1-D 였는데, reshape을 통해 2x3행렬로 바뀜요 개꿀

array([[0., 1., 2.],
       [3., 4., 5.]])

In [18]:
a.transpose()

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [19]:
a.flatten() #짜부시키기

array([0., 1., 2., 3., 4., 5.])

In [20]:
a=np.array([1,2],float)
b=np.array([3,4,5,6],float)
c=np.array([7,8,9],float)
np.concatenate((a,b,c)) #전부다 합치는 함수입니다.

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [21]:
a=np.array([1,2,3],float)

In [22]:
b=np.array([5,2,6],float)

In [23]:
print(a+b)
print(a-b)
print(a*b)
print(b/a)
print(a%b)
print(b**a)

[6. 4. 9.]
[-4.  0. -3.]
[ 5.  4. 18.]
[5. 1. 2.]
[1. 0. 3.]
[  5.   4. 216.]


In [24]:
a+b #이거는 operand들이 Shape이 같아야합니다.

array([6., 4., 9.])

In [25]:
a=np.array([1,2,3],float)
b=np.array([4,5,6],float)

In [26]:
a+b

array([5., 7., 9.])

In [27]:
#Numpy 오브젝트와 그냥 List는 달라요
a=[1,2,3,4]
a*2
b=[1,2,3,4]
npa=np.array(a)
npb=np.array(b)
npa+npb

array([2, 4, 6, 8])

In [28]:
a=np.array([1,4,5],int)
for x in a:
    print(x)

1
4
5


In [29]:
a=np.array([[1,2],[3,4],[5,6]],float)
for x in a:
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [30]:
np.array(range(1,7)).reshape(2,3)
np.array(range(7,13)).reshape(2,3)
np.array(range(13,19)).reshape(2,3)
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [31]:
a=np.array([2,4,3],float)
a.sum()

9.0

In [32]:
a.prod()

24.0

In [33]:
a=np.array([2,1,9],float)

In [34]:
a.mean()

4.0

In [35]:
a.var()

12.666666666666666

In [36]:
a.std()
np.median(a)

2.0

In [37]:
x=np.array([[1,2],[3,4]])
print(np.sum(x))#x.sum()
print(np.sum(x,axis=0))#각 Column에 대한 합계를 계산
#x.sum(axis=0)
print(np.sum(x,axis=1))#각 Row에 대한 합계를 계산
x.sum(axis=1) #출력형식은 다릅니다. 리턴오브젝트가 print는 리스트로, x.sum한거는 numpy오브젝트로 나옵니다.

10
[4 6]
[3 7]


array([3, 7])

In [38]:
npa

array([1, 2, 3, 4])

## Numpy Array Statistics

In [39]:
npa=np.array([[1,2,3],[4,5,6],[7,8,9]])
npa.sum()

45

In [40]:
#상관계수 공분산
a=np.array([[1,2,1,3],[5,3,1,8]],float)
c=np.corrcoef(a)
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

## Linear Algebra and Numpy

In [41]:
a=np.array([1,2,3],float)
b=np.array([0,1,1],float)
np.dot(a,b) #inner product

5.0

In [42]:
a=np.array([[0,1],[2,3]],float)
b=np.array([2,3],float)
c=np.array([[1,1],[4,0]],float)

#벡터연산은 똑같아요.
np.dot(b,a)
np.inner(b,a)

array([ 3., 13.])

In [43]:
np.inner(a,b)

array([ 3., 13.])

In [44]:
np.dot(a,b)

array([ 3., 13.])

In [45]:
np.inner(a,c)#

array([[1., 0.],
       [5., 8.]])

In [46]:
np.dot(a,c)

array([[ 4.,  0.],
       [14.,  2.]])

In [47]:
np.inner(a,c)#np.dot(c,a)

array([[1., 0.],
       [5., 8.]])

In [48]:
points=[[9,2,8],[4,7,2],[3,4,4],[5,6,9],[5,0,7],[8,2,7],[0,3,2],[7,3,0],[6,1,1],[2,9,6]]

In [49]:
qPoint=[4,5,3]

In [50]:
minldx=-1
minDist=-1
#for idx,point in enumerate(points):
#    dist=sum([(dp-dq)**2 for dp,dq in zip(point,qPoint)])**0.5
#    if dist<minDist or minDist<0: