# Ch 17. Python Modules and Packages

## Utilizing Modules

라이브러리와 모듈은 우리가 혼용하는 같은 단어입니다   
우리가 만들어 놓은 새로운 모듈, 함수를 불러오고 싶으면..  
우리가 만들어놓은 새로운 함수를 어디에 깔아놓았는지 알아야합니다.  

System: Python File  
O/S : Window  
를 이야기합니다 이들로부터 도움을 받고싶고 요구하려면 이들과 명령어를 통해서 소통해야해요

In [1]:
#mod1,py로 저장한후
#def sum(a,b):
#    return a+b
#저장위치로 이동한다음 import mod1을 하면 sum이 그냥 리콜된다.

def safe_sum(a,b):    
from mod1 import sum, safe_sum  
from mod1 import *  
두개는 차이가 있습니다. 대충 불러오는건지 아니면 특정하게 불러오는지입니다.  
특정하게 불러올시에는 이름을 즉각적으로 사용가능하나  
전체적으로 불러올때는 mod1.function 식으로 함수를 불러와야합니다.  

__테스트 하기 귀찮으면 쓰는 방법__

In [2]:
def sum(a,b):
    return a+b
def safe_sum(a,b):
    if type(a) !=type(b):
        print("더할 수 있는 게 아닙니다.")
        return
    else:
        result=sum(a,b)
    return result
if __name__ =="__main__":#지금 수행하는 프로그램의 이름
    """
    지금 돌리는 프로그램이 메인 프로그램이면 이라고 해석해도 좋고
    이 프로그램이 내 쉘에서 돌아간다면 이라는 뜻입니다.
    이 안에 있는 함수에 해당하는 것들을 연습하는게 실행됩니다
    이 프로그램이 내가 만든 쉘에서 돌아간다면 얘가 돌아갑니다
    내가 만든 함수들의 테스트를 해줍니다.
    그런데 요부분이 옆에 친구한테 주고 사용하게 하려면
    다른 shell에서 혹은 python에서 import해서 써야합니다.
    라이브러리로 쓰게 되는 얘는 이 쉘의 입장에서는 main이 아닙니다.
    그래서 if문은 실행이 안됩니다. 메인이 아니니까요!!
    """
    print(safe_sum('a',1))
    print(safe_sum(1,4))
    print(sum(10,10.4))

더할 수 있는 게 아닙니다.
None
5
20.4


In [6]:
PI=3.141582
#Numpy안에도 다양한 클래스들이 존재합니다.
class Math:
    def solv(self,r):
        return PI*(r**2)
def sum(a,b):
    return a+b
if __name__=="__main__":
    print(PI)
    a=Math()
    print(a.solv(PI))
    print(sum(PI,4.4))

#import mod2
#result=mod2.sum(3,4)
#print(result)

3.141582
31.005961241219392
7.541582


In [9]:
#모듈을 불러오는 또 다른 방법
import sys
"""
찾아달라고하면 찾아보는 path들 입니다
우리가 또필요하면요 py파일이 있는 곳까지의 주소를 append 해야합니다
이거 자체들이 리스트인데, 내가 짜는 프로그램들이 있는 곳을 append 해주면 됩니다.
"""
#sys.path.appenc("C:/Python/SNU_Python") 이런식으로 추가가능합니다
sys.path.append("C:/Users/renz/SNU_Python")
#sys.path.remove("C:/Users/renz/SNU_Python")
sys.path

['',
 'C:\\ProgramData\\Anaconda3\\python36.zip',
 'C:\\ProgramData\\Anaconda3\\DLLs',
 'C:\\ProgramData\\Anaconda3\\lib',
 'C:\\ProgramData\\Anaconda3',
 'C:\\Users\\renz\\AppData\\Roaming\\Python\\Python36\\site-packages',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\renz\\.ipython',
 'C:/Users/renz/SNU_Python']

## Python Package

가상의 게임 패키지의 예  
game /  
>_ _ init _ _ .py  #게임 밑에있는 아이들 사운드, 그래픽, 플레이가 얘네들의 구성원들이야 하는 겁니다.  
>sound/  
>>_ _ init _ _ .py #같은게 있기만하면, 같은 레벨에 있는 아이들은 서로 의미가 있는 아이들이야 play밑의 구성원들이야  
>>echo.py  
>>wav.py

>graphic/  
>>_ _ init _ _ .py  
>>screen.py  
>>render.py  

> play/  
>>_ _ init _ _ .py   
>>run,py  
>>test.py  
        

_ _ init _ _ .py로 구분하지 않아도 파이썬 버전이 올라감에 따라 알아서 처리해주고 불러와주지만,  
.py로 구분하여 패키지안에 배치하는 것에 유익함이 있습니다.

from Library import * 이 라이브러리 속에있는 모듈 전부다 임포트 할테야! 입니다  
impoort game.sound.echo  
game.sound.echo.echo_test()  
_ _ all _ _ 

## PyPI and Pip: Automatic Installation

Pandas, Numpy 만 가지고 데이터 분석하는데 왜 이게 기본 라이브러리가 아닐까..   
이제 Numpy, Pandas, matplotlib 등등 전부다 Standard Library가 아닌데, 반드시 해야해    
기본 라이브러리는 모든 사람이 사용할수있는 것이 중요해요    
데이터분석가들에게 필요한것말고요.    

#IDLE - Standard Lib   
뚱뚱한 파이썬이 만들고 싶어서 아나콘다가 됬어요   
  
Graphical User Interface 이지요    
기본 파이썬에 인기있는 여러모듈을 수십개를 만들어 놓은 Anaconda 가 있어요    
얘의 기본 IDE 는 Spyder 에요   

파이썬 개발자들은 자신들의 개발한 파이썬 모듈들을 PyPI에 업로드합니다  
홈페이지에 접속하지 않고도 pip를 통해서 원하는 모듈을 다운로드 할수 있어요.  

pip 도 옛날에는 설치했었어야했어요. 요즘에는 디폴트로 다 깔아줍니다.  

# The Python Standard Library

__The Python Language Reference__

__Python Standard Library Reference Manual__


# Numpy

In [18]:
data=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [19]:
def sum_matrix(table):
    for row in range(0,len(table)):
        for col in range(0,len(table[row])):
            sum +=table[row][col]
    return sum

In [20]:
from statistics import *
print(mean([2,6,20]))

9.333333333333334


In [21]:
import numpy as np

In [22]:
np.ndarray([5,5])

array([[6.23042070e-307, 0.00000000e+000, 1.72451033e-307,
        1.44635488e-307, 1.37962320e-306],
       [1.29060871e-306, 7.56603881e-307, 7.56599807e-307,
        8.90104239e-307, 1.24610383e-306],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306],
       [1.29060531e-306, 6.89805151e-307, 7.56592338e-307,
        6.89807188e-307, 1.37961302e-306],
       [8.45559303e-307, 1.06811422e-306, 1.05694828e-307,
        2.22522596e-306, 2.10081501e-312]])

## Numpy Array Creation
Numpy Array data type

In [23]:
a=np.array([1,4,5,8],float)
print(a)
type(a)

[1. 4. 5. 8.]


numpy.ndarray

In [24]:
a=np.array([[1,2,1,3],[5,3,1,8]])
a

array([[1, 2, 1, 3],
       [5, 3, 1, 8]])

In [25]:
c=np.corrcoef(a)
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [26]:
a=np.array([[1,2,3],[4,5,6]],float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])